---
include:
# ESB-only experiment. Build normal BLE firmware from its original branch/profile.
  - board: xiao_ble//zmk
    shield: Polaris_L_ESB rgbled_adapter
    snippet: JOY battery-voltage-divider-oversampling studio-rpc-usb-uart cdc-boot polaris-esb
    artifact-name: Polaris_L_JOY_ESB_USB

  - board: xiao_ble//zmk
    shield: Polaris_R_ESB rgbled_adapter
    snippet: TB_R zmk-usb-logging cdc-debug-boot polaris-esb
    artifact-name: Polaris_R_TB_ESB
