# Analog input settings for sensors
CONFIG_ADC=y
CONFIG_ADC_ASYNC=y
# CONFIG_ZMK_BATTERY_NRF_VDDH_OVERSAMPLING_VALUE=0

# DYA Analog Input Module settings
CONFIG_DYA_ANALOG_INPUT=y
CONFIG_DYA_ANALOG_INPUT_STUDIO_RPC=y

# Rotary encoder configuration
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
