# Studio and custom RPC features used by the standard Polaris modules.
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR_STUDIO_RPC=y
CONFIG_ZMK_RUNTIME_SENSOR_ROTATE_STUDIO_RPC=y
CONFIG_INPUT_IQS9151_STUDIO_RPC=y
CONFIG_ZMK_BLE_MANAGEMENT=y
CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SETTINGS_RPC_STUDIO=y
CONFIG_ZMK_BLE_MANAGEMENT_STUDIO_RPC=y
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_ZMK_STUDIO_RPC_RX_BUF_SIZE=512
CONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE=512
